archetypeDir = "archetypes"
baseurl = "http://alvinblog.github.io"
buildDrafts = false
buildExpored = false
buildFuture = false
canonifyURLs = true
contentDir = "content"
dataDir = "data"
disable404 = false
disableHugoGeneratorInject = false
disableRSS = false
disableSitemap = false
enableEmoji = true
enableGitInfo = false
enableMissingTranslationPlaceholders = false
enableRobotsTXT = true
layoutDir = "layouts"
publishDir = "public"
theme = "hello-friend-ng"
title = "Alvin Indra"
[author]
name = "Alvin Indra"
[blackfriday]
hrefTargetBlank = true
[languages.en]
copyright = ""
keywords = "Personal, Catatan, Inspirasi, Tentangku"
readOtherPosts = "Baca yang lainnya"
subtitle = "Hai, Selamat datang di Dunia Tulisku :)"
title = "Alvin Indra"
[[languages.en.menu.main]]
identifier = "blog"
name = "Blog"
url = "/posts"
[[languages.en.menu.main]]
identifier = "tentang"
name = "Tentang"
url = "/about"
[languages.en.params.logo]
logoHomeLink = "/"
logoText = "alvinblog.me"
[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects"
weight = 3
[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/posts"
weight = 2
[[menu.main]]
identifier = "tentang"
name = "Tentang"
url = "/about"
weight = 1
[params]
contentTypeName = "posts"
dateform = "Jan 2, 2006"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04 -0700"
dateformShort = "Jan 2"
defaultTheme = "dark"
description = "Homepage and blog by Alvin Indra"
homeSubtitle = "Hai, Selamat Datang Di Dunia Tulisku"
images = [""]
keywords = "homepage, blog, science, informatics, development, programming"
[[params.social]]
name = "twitter"
url = "https://twitter.com/alvinindrapra"
[[params.social]]
name = "email"
url = "mailto:alvinindrap@gmail.com"
[[params.social]]
name = "github"
url = "https://github.com/alvinindrap"
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/alvinindra"
[permalinks]
posts = "/posts/:year/:month/:title/"
[taxonomies]
category = ""
tag = "tags"
